# .gitlab-ci.yml

image: rust:latest

variables:
  CARGO_HOME: ${CI_PROJECT_DIR}/.cargo

cache:
  paths:
    - .cargo/registry
    - .cargo/git
    - .cargo/bin
    - target/
  key: ${CI_COMMIT_REF_SLUG}

check:
  script:
    - cargo check --workspace
    - cargo check -p axi-dma --features portable-atomic
    - cargo check -p axi-uart16550 --features portable-atomic
    - cargo check -p axi-uartlite --features portable-atomic

build:
  script:
    - cargo build --workspace
    - cargo build -p axi-dma --features portable-atomic
    - cargo build -p axi-uart16550 --features portable-atomic
    - cargo build -p axi-uartlite --features portable-atomic

clippy:
  script:
    - rustup component add clippy
    - cargo clippy --workspace -- -D warnings

fmt:
  script:
    - rustup component add rustfmt
    - cargo fmt --all -- --check

docs:
  before_script:
    - rustup install nightly
  script:
    - RUSTDOCFLAGS="--cfg docsrs -Z unstable-options --generate-link-to-definition" cargo +nightly doc --workspace --no-deps

cross-check:
  before_script:
    - rustup target add armv7-unknown-linux-gnueabihf
    - rustup target add armv7a-none-eabihf
  script:
    - cargo build --workspace --target armv7-unknown-linux-gnueabihf
    - cargo build --workspace --target armv7a-none-eabihf
